const items =[
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: 'https://media.istockphoto.com/id/161170090/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=8EctScsN7q5UmxeXPNBnYN1eFmJmgmp2bE0OIq_czwM=',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: 'https://resdiaryportal.wpengine.com/wp-content/uploads/2022/02/lotus-double-bay-restaurant.jpeg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
      },
      {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 6.99,
        img: 'https://sf1.mariefranceasia.com/wp-content/uploads/sites/7/2015/11/Cake-Spade-413x410.jpg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
      },
      {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: 'https://vismaifood.com/storage/app/uploads/public/0bb/75b/a1d/thumb__700_0_0_0_auto.jpg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      },
      {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: 'https://img.livestrong.com/630x/clsd/getty/b30a4dabcc634e67b0721d1851f901da.jpg?type=webp',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      },
      {
        id: 6,
        title: 'oreo dream',
        category: 'shakes',
        price: 18.99,
        img: 'https://sweetandsavorymeals.com/wp-content/uploads/2019/01/Dream-Extrate-Oreo-Cheesecake-5-1168x540.jpg.webp',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
      {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: 'https://www.thespruceeats.com/thmb/E2D_w-cbUSecMm3hkufQRO1Jh-w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/organic-turkey-bacon-ranch-sandwich-2937584-hero-01-af2cc4f391f34320ac9020bebd009f84.jpg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
      },
      {
        id: 8,
        title: 'indian classic',
        category: 'lunch',
        price: 12.99,
        img: 'https://www.kayak.co.uk/news/wp-content/uploads/sites/5/2022/10/THEME_FOOD_INDIAN-CUISINE-GettyImages-526749337-1-820x656.jpg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
      },
      {
        id: 9,
        title: 'quarantine buddy',
        category: 'shakes',
        price: 16.99,
        img: 'https://www.khuab.com/wp-content/uploads/2020/06/breakfast-690128_1920-768x512.jpg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
]

export default items;
